#!/bin/bash

########################################################################
#                             T R O K A M
#                        Internet Search Engine
#
#  Copyright (C) 2018, Nicolas Slusarenko
#                      nicolas.slusarenko@trokam.com
#
#  This file is part of Trokam.
#
#  Trokam is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Trokam is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Trokam. If not, see <http://www.gnu.org/licenses/>.
########################################################################

ZERO=0
while [ $ZERO -eq 0 ]
do
    CRUNCHER_LOG=$HOME'/trokam/log/cruncher_'$(date +%Y_%m_%d_%H_%M)'.log'
    START=$(date +%s.%N)
    ./bin/cruncher --pages-limit 1000 > $CRUNCHER_LOG 2>&1
    state=$?
    END=$(date +%s.%N)
    DIFF=$(echo "$END - $START" | bc)
    echo "Time elapsed= " $DIFF >> $CRUNCHER_LOG

    FEEDER_LOG=$HOME'/trokam/log/feeder_'$(date +%Y_%m_%d_%H_%M)'.log'
    START=$(date +%s.%N)
    ./bin/feeder > $FEEDER_LOG 2>&1
    END=$(date +%s.%N)
    DIFF=$(echo "$END - $START" | bc)
    echo "Time elapsed= " $DIFF >> $FEEDER_LOG

    if [ $state -gt 0 ]
    then
        echo "script is terminated" >> $CRUNCHER_LOG
        exit 1
    fi
done
